version: "3.7"

networks: 
  cardealer:

services:

  cardealer_mongo:
    container_name: cardealer_mongo
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - 27018:27017
    networks:
      - cardealer

  cardealer_api:
    container_name: cardealer_api
    build: 
      context: ./api
    restart: always
    image: sreetejaact/actchain-cardealerapi
    volumes:
      - ./api:/usr/src/app
    ports:
      - 4003:4003
    environment:
      - EPASS=passofemail
    depends_on:
      - cardealer_mongo
    networks: 
      - cardealer

  cardealer_app:
    container_name: cardealer_app
    build: 
      context: ./app
    image: sreetejaact/actchain-cardealerapp
    restart: always
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - cardealer_api
    ports:
      - 3003:80
    networks: 
      - cardealer